### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by CoderoidAcademy** [iQueSoft/iQuePhoto#14]
hi, when i use Filters Button, app crash and i get this error

Attempt to invoke virtual method 'android.graphics.Bitmap net.iquesoft.iquephoto.core.ImageEditorView.getAlteredImageBitmap()' on a null object reference
        at net.iquesoft.iquephoto.ui.fragments.FiltersFragment.provideFilterPresenter(FiltersFragment.java:41)
        at net.iquesoft.iquephoto.ui.fragments.FiltersFragment$$PresentersBinder$mPresenterBinder.providePresenter(FiltersFragment$$PresentersBinder.java:24)
        at com.arellomobile.mvp.MvpProcessor.getMvpPresenter(MvpProcessor.java:52)
        at com.arellomobile.mvp.MvpProcessor.getMvpPresenters(MvpProcessor.java:99)
        at com.arellomobile.mvp.MvpDelegate.onCreate(MvpDelegate.java:101)
        at net.iquesoft.iquephoto.extras.MvpAppCompatFragment.onCreate(MvpAppCompatFragment.java:25)
        at net.iquesoft.iquephoto.ui.fragments.ToolFragment.onCreate(ToolFragment.java:15)
        at net.iquesoft.iquephoto.ui.fragments.FiltersFragment.onCreate(FiltersFragment.java:61)

why?
note, i using Android api 28 and Android X and gradle 3.4.1

**Comment by saadhussain420** [comment]
Check the path or the input bitamp you are passing to the filters, it appears to be null.
